### ISSUE TITLE
add idle logout

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/console.dot#29]
Configure c-ws to set a session idle time of 15 minutes by default.

**Comment by martinpitt** [comment]
This does not work -- IdleTimeout only applies to "standard logins", i.e. when going through the login page. That's not the case for our scenario here, as we don't authenticate Cockpit.

**Comment by marusak** [comment]
But we need some way of "idle timeout". Do we have some other ideas @martinpitt or should we at least track this somewhere? (like start bridge with --timeout option or so?)

**Comment by martinpitt** [comment]
@marusak : If we want idle timeout for such logins, we need to [change it in the shell](https://github.com/cockpit-project/cockpit/blob/723efb6af4f4aa63c609293cc967c1c0768f26e7/pkg/shell/base_index.js#L576) -- either make the option apply to all  logins, or add another config value/option for it. The bridge has traffic all the time (like d-bus watches or pings), it will never be idle.
