### ISSUE TITLE
clean up session pod on idle/disconnect

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/console.dot#30]
Detect browser disconnects or explicit logouts, and clean up the session container and session table accordingly. The latter must keep the session as "closed" at least for a while, to get a correct UI. See issue #60

The cleanup can also happen in a regular "garbage collection sweep", that is handled in issue #54. For this issue, just consider the session container. Ideally cockpit-ws would time out and stop itself, then we can mark the session containers as auto-delete. But if c-ws does not do that, we need to kill the containers explicitly.

**Comment by marusak** [comment]
Can we listen on events and recognize exactly when session goes down so we have better estimates how long sessions take?

**Comment by martinpitt** [comment]
@marusak: We have the exact time when the user clicks "Logout". When they close the tab or change to a non-cockpit URL, then the /cockpit/socket will time out after 10s (not getting ping/pong any more). That's still fairly precise, I'd say :grin:

**Comment by martinpitt** [comment]
Prerequisite for this is PR #52

**Comment by martinpitt** [comment]
> Ideally cockpit-ws would time out and stop itself

It does not do that, see PR #61. So we need to actively kill the session container.

**Comment by martinpitt** [comment]
I have an [initial implementation](https://github.com/cockpit-project/console.dot/commit/6826dc35bc363f633ce7c4a95e2eb04093a11110) which works fine with podman.

However, not on k8s - the `deployer` service account name isn't permitted to remove pods:

```
$ curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X DELETE ${APISERVER}/api/v1/namespaces/cockpit-dev/pods/session-1974faf3-a88c-425d-b4b3-d16a197d8c53
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "pods \"session-1974faf3-a88c-425d-b4b3-d16a197d8c53\" is forbidden: User \"system:serviceaccount:cockpit-dev:deployer\" cannot delete resource \"pods\" in API group \"\" in the namespace \"cockpit-dev\"",
  "reason": "Forbidden",
  "details": {
    "name": "session-1974faf3-a88c-425d-b4b3-d16a197d8c53",
    "kind": "pods"
  },
  "code": 403
}
```

We don't have access to the Roles/RoleBindings in the project, so we cannot create a custom service account either. But maybe we even shouldn't -- it would still be nicer if the session containers could decide for themselves when to exit. So perhaps we can fix this in cockpit properly, and in the meantime let `websocket-session.py` kill all processes in the container?
