### ISSUE TITLE
make wait and closed pages tasteful

### ISSUE THREAD

**Issue by martinpitt** [cockpit-project/console.dot#59]
Right now these are very simple and ugly stubs. They have the required functionality, but look nothing like a real product :grin:

**Comment by jelly** [comment]
If we only want to do some basic styling with Patternfly, the [Developer guide](https://www.patternfly.org/v4/get-started/develop#htmlcss):

```
npm install @patternfly/patternfly --save
```

The full css is a bit big for a simple loading page:

```
[jelle@t14s][~/projects/console.dot/testfrontend]%ls -lh node_modules/@patternfly/patternfly/patternfly.css
-rw-r--r-- 1 jelle jelle 1.7M Oct 12 10:57 'node_modules/@patternfly/patternfly/patternfly.css'
```

We want to show a loading page, maybe like the [example](https://www.patternfly.org/v4/components/table/html-demos/loading-state-demo/).

Simple try out:

![image](https://user-images.githubusercontent.com/67428/195309366-9e09eb0d-cf20-4d1f-ab0f-c4750571bd7b.png)


## Questions

- [ ] Do we need to tranlsate this web page?

**Comment by jelly** [comment]
[Screencast from 12-10-22 14:24:41.webm](https://user-images.githubusercontent.com/67428/195342277-c3e58673-addf-4d92-a624-0024928af5cc.webm)
